extends:
  - standard
  - eslint:all
  - plugin:react/all
plugins:
  - standard
  - promise
  - react
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  react/no-danger:
    - 0
