service: sls-wordpress-frontend
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
#  region: us-east-1

package:
  include:
    - node_modules/
    - config/
    - src/

custom:
  webpackIncludeModules: true # enable auto including modules

functions:
  index:
    handler: src/index.index
    events:
      - http:
          path: /
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
  post:
    handler: src/index.post
    events:
      - http:
          path: /blog/{slug}
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
            statusCodes:
              201:
                pattern: ''
              404:
                pattern: '.*[404].*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
                headers:
                  Content-Type: "'text/html'"
